### ISSUE TITLE
Error - when hosting two plugins - typedoc-plugin-markdown and typedoc-plugin-pages

### ISSUE THREAD

**Issue by yboujraf** [tgreyuk/typedoc-plugin-markdown#123]
Dear

I have an error when I have :

## The two plugins are installed :

- https://www.npmjs.com/package/typedoc-plugin-markdown
- https://www.npmjs.com/package/typedoc-plugin-pages

```
Loaded plugin C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc-plugin-markdown
Loaded plugin C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc-plugin-pages
```

## The error message :

```
desk01@BY_DESKTOP_01 MINGW64 /c/Git/by/smh - connectors/smh-template-connector-lib (feature/SMH-66-add-connector-client-server-socke)
$ npm run docs:pages

> @by/smh-template-connector-lib@0.0.0-development docs:pages C:\Git\by\smh - connectors\smh-template-connector-lib
> rimraf ./docs/dist/docs-pages && typedoc --options ./typedoc/typedoc-config-pages.ts

Loaded plugin C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc-plantuml
Loaded plugin C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc-plugin-external-module-name
Loaded plugin C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc-plugin-markdown
Loaded plugin C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc-plugin-pages

Using TypeScript 3.8.3 from C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typescript\lib
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, stat 'C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc-plugin-markdown\dist\resources\assets'
    at Object.statSync (fs.js:982:3)
    at Object.statSync (C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\graceful-fs\polyfills.js:307:34)
    at getStatsSync (C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\fs-extra\lib\util\stat.js:58:18)
    at Object.checkPathsSync (C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\fs-extra\lib\util\stat.js:90:33)
    at Object.copySync (C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\fs-extra\lib\copy-sync\copy-sync.js:24:38)
    at AssetsPlugin.onRendererBegin (C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc\dist\lib\output\plugins\AssetsPlugin.js:28:16)



    at C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc\dist\lib\utils\events.js:259:33
    at triggerApi (C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc\dist\lib\utils\events.js:110:13)
    at Renderer.trigger (C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc\dist\lib\utils\events.js:252:13)
    at Renderer.render (C:\Git\by\smh - connectors\smh-template-connector-lib\node_modules\typedoc\dist\lib\output\renderer.js:33:14) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\Git\\by\\smh - connectors\\smh-template-connector-lib\\node_modules\\typedoc-plugin-markdown\\dist\\resources\\assets'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @by/smh-template-connector-lib@0.0.0-development docs:pages: `rimraf ./docs/dist/docs-pages && typedoc --options ./typedoc/typedoc-config-pages.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @by/smh-template-connector-lib@0.0.0-development docs:pages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ybouj\AppData\Roaming\npm-cache\_logs\2020-05-14T19_19_19_232Z-debug.log
```

Best Regards
Youssef

**Comment by tgreyuk** [comment]
Just reviewing old tickets. This isn't related to 2 plugins running at same time. The error appears to be the file system is trying to access an 'assets' folder which doesn't exist for the markdown theme (maybe theme --minimal set in an options file or something). This error should no longer happen in v3.0..
