### ISSUE TITLE
docusaurus: sidebars.js should be created before docusaurus trying to access it

### ISSUE THREAD

**Issue by felipecrs** [tgreyuk/typedoc-plugin-markdown#151]
I don't know if this is possible according to the plugin's lifecycle, but when you run `docusaurus build` without a `sidebars.js` file, it fails, despite TypeDoc was about to create one.

```console
$ docusaurus build
Creating an optimized production build...
Error: Cannot find module './sidebars.js'
Require stack:
- /workspaces/megatar/website/docusaurus.config.js
- /workspaces/megatar/website/node_modules/@docusaurus/core/lib/server/config.js
- /workspaces/megatar/website/node_modules/@docusaurus/core/lib/server/index.js
- /workspaces/megatar/website/node_modules/@docusaurus/core/lib/commands/build.js
- /workspaces/megatar/website/node_modules/@docusaurus/core/lib/index.js
- /workspaces/megatar/website/node_modules/@docusaurus/core/bin/docusaurus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at Object.<anonymous> (/workspaces/megatar/website/docusaurus.config.js:38:32)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Object.module.exports [as default] (/workspaces/megatar/website/node_modules/import-fresh/index.js:31:59)
    at Object.loadConfig [as default] (/workspaces/megatar/website/node_modules/@docusaurus/core/lib/server/config.js:24:48)
    at loadContext (/workspaces/megatar/website/node_modules/@docusaurus/core/lib/server/index.js:48:40)
    at Object.load (/workspaces/megatar/website/node_modules/@docusaurus/core/lib/server/index.js:77:21)
    at build (/workspaces/megatar/website/node_modules/@docusaurus/core/lib/commands/build.js:30:34)
    at /workspaces/megatar/website/node_modules/@docusaurus/core/bin/docusaurus.js:73:5
    at Command.<anonymous> (/workspaces/megatar/website/node_modules/@docusaurus/core/bin/docusaurus.js:97:23)
    at Command.listener (/workspaces/megatar/website/node_modules/@docusaurus/core/node_modules/commander/index.js:370:29)
```

To work around it I have to:

```console
# Create the file, so the first build does not fails
$ touch sidebars.js
# This makes the plugin generate the sidebars file, but the build process does not get it in time
$ docusaurus build
# Build again, so the build process will take the previous sidebars.js file generated
$ docusaurus build
```

**Comment by tgreyuk** [comment]
It does appear that Docusaurus attempts to load the sidebars.js before the plugins and associated plugin lifecycles. A ticket with a promising title was raised ( https://github.com/facebook/docusaurus/issues/2740 ), but the response only answers how to load the correct presets with a sidebar.js rather that handle any auto generated sidebars.js.  I will look into it more not sure of the fix at plugin level yet.

**Comment by jsamr** [comment]
I have the feeling that I didn't run into this problem after configuring the plugin to generate a separate sidebar file and requiring it (what we discussed in #144); not completely clear if other elements of my setup are responsible for this improvement though.

**Comment by felipecrs** [comment]
Just to note: `docusaurus start` works fine since it watches for changes in the files and automatically reloads.

**Comment by tgreyuk** [comment]
@felipecrs by moving the logic from the lifecycle apis to the plugin initialization it (appears) solves the sidebar generation issue. There seems no other way to do it with the current lifecyce architecture and as we are just generating static pages we don't need anything from the lifecycle although it would be nice if there was another event to handle this. if you could sanity check this on 0.2.0 when you have some time. thanks....

**Comment by felipecrs** [comment]
Yes, it's working now! 🎉

**Comment by felipecrs** [comment]
Actually, the issue of `docusaurus` trying to access the `sidebars.js` before it gets generated still exists, however, the new version of this plugin advises using a different `sidebars.js` file (not managed by this plugin), so it solves that.

Nonetheless, the issue of Docusaurus using the previously generated sidebars was indeed solved, so I was able to remove my workaround about building twice.

**Comment by tgreyuk** [comment]
ok sounds promising. i will close this one for now. if we encounter any more issues around sidebar we can open another ticket.
