### ISSUE TITLE
Error loading typedoc-plugin-markdown in monorepo

### ISSUE THREAD

**Issue by xuchen509** [tgreyuk/typedoc-plugin-markdown#171]
Hello, I just started using this plugin and I'm having issues loading typedoc plugins. I have a mono repo setup like this 
```
        my-framework
             |_ clients
             | _ hooks
             |_ dosc-site (docusaurus)
```
My package.json inside docs-site has all required plugins listed under devDependencies
```
   ...
"devDependencies": {
        "@docusaurus/module-type-aliases": "^2.0.0-alpha.69",
        "@splunk/swp-ui-config": "lib:infra/swp-ui-config",
        "@tsconfig/docusaurus": "^1.0.2",
        "@types/react": "^16.9.35",
        "@types/react-helmet": "^6.1.0",
        "@types/react-router-dom": "^5.1.6",
        "docusaurus-plugin-typedoc": "^0.4.1",
        "prettier": "^2.0.4",
        "typescript": "^3.8.3",
         "typedoc": "^0.19.2",
        "typedoc-plugin-markdown": "^3.1.1",
    }
...
```
When I run `docusaurus start` within docs-site, I'm getting these errors:
```Starting the development server...
Error: The plugin typedoc-plugin-markdown could not be loaded.

Error: typedoc tried to access typedoc-plugin-markdown, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: typedoc-plugin-markdown (via "typedoc-plugin-markdown")
Required by: typedoc@virtual:70a03ccb14b541f70e4d3744aaa0f16e377c9d9d131feb425cb946e1119e22709ecbad502900951025e12d3a10d86d55321f322623428ff774802a5e562cb541#npm:0.19.2 (via /.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/lib/utils/)

Require stack:
- /.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/lib/utils/plugins.js
- /.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/lib/utils/index.js
- /.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/lib/models/reflections/project.js
- /.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/lib/models/reflections/index.js
- /.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/lib/models/index.js
- /.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/lib/converter/context.js
- /.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/lib/converter/index.js
- /.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/lib/application.js
- /.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/index.js
- /.../my-framework/.yarn/$$virtual/docusaurus-plugin-typedoc-virtual-e76b444941/0/cache/docusaurus-plugin-typedoc-npm-0.4.1-f96b19b39a-57ee984433.zip/node_modules/docusaurus-plugin-typedoc/dist/plugin.js
- /.../my-framework/.yarn/$$virtual/docusaurus-plugin-typedoc-virtual-e76b444941/0/cache/docusaurus-plugin-typedoc-npm-0.4.1-f96b19b39a-57ee984433.zip/node_modules/docusaurus-plugin-typedoc/dist/index.js
- /.../my-framework/.yarn/$$virtual/@docusaurus-core-virtual-823a146269/0/cache/@docusaurus-core-npm-2.0.0-alpha.f37987f32-0083f3f5a5-294a73ee2e.zip/node_modules/@docusaurus/core/lib/server/plugins/init.js
- /.../my-framework/.yarn/$$virtual/@docusaurus-core-virtual-823a146269/0/cache/@docusaurus-core-npm-2.0.0-alpha.f37987f32-0083f3f5a5-294a73ee2e.zip/node_modules/@docusaurus/core/lib/server/plugins/index.js
- /.../my-framework/.yarn/$$virtual/@docusaurus-core-virtual-823a146269/0/cache/@docusaurus-core-npm-2.0.0-alpha.f37987f32-0083f3f5a5-294a73ee2e.zip/node_modules/@docusaurus/core/lib/server/index.js
- /.../my-framework/.yarn/$$virtual/@docusaurus-core-virtual-823a146269/0/cache/@docusaurus-core-npm-2.0.0-alpha.f37987f32-0083f3f5a5-294a73ee2e.zip/node_modules/@docusaurus/core/lib/commands/build.js
- /.../my-framework/.yarn/$$virtual/@docusaurus-core-virtual-823a146269/0/cache/@docusaurus-core-npm-2.0.0-alpha.f37987f32-0083f3f5a5-294a73ee2e.zip/node_modules/@docusaurus/core/lib/index.js
- /.../my-framework/.yarn/$$virtual/@docusaurus-core-virtual-823a146269/0/cache/@docusaurus-core-npm-2.0.0-alpha.f37987f32-0083f3f5a5-294a73ee2e.zip/node_modules/@docusaurus/core/bin/docusaurus.js
    at internalTools_makeError (/.../my-framework/.pnp.js:31611:34)
    at resolveToUnqualified (/.../my-framework/.pnp.js:32576:23)
    at resolveRequest (/.../my-framework/.pnp.js:32668:29)
    at Object.resolveRequest (/.../my-framework/.pnp.js:32746:26)
    at Function.external_module_.Module._resolveFilename (/.../my-framework/.pnp.js:31844:34)
    at Function.external_module_.Module._load (/.../my-framework/.pnp.js:31709:48)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at PluginHost.load (/.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/lib/utils/plugins.js:24:34)
    at Application.bootstrap (/.../my-framework/.yarn/$$virtual/typedoc-virtual-fc1ef5f578/0/cache/typedoc-npm-0.19.2-67686083da-fc33909c4d.zip/node_modules/typedoc/dist/lib/application.js:52:22)
    at pluginDocusaurus (/.../my-framework/.yarn/$$virtual/docusaurus-plugin-typedoc-virtual-e76b444941/0/cache/docusaurus-plugin-typedoc-npm-0.4.1-f96b19b39a-57ee984433.zip/node_modules/docusaurus-plugin-typedoc/dist/plugin.js:36:13)
    at /.../my-framework/.yarn/$$virtual/@docusaurus-core-virtual-823a146269/0/cache/@docusaurus-core-npm-2.0.0-alpha.f37987f32-0083f3f5a5-294a73ee2e.zip/node_modules/@docusaurus/core/lib/server/plugins/init.js:71:48
    at Array.map (<anonymous>)
    at Object.initPlugins [as default] (/.../my-framework/.yarn/$$virtual/@docusaurus-core-virtual-823a146269/0/cache/@docusaurus-core-npm-2.0.0-alpha.f37987f32-0083f3f5a5-294a73ee2e.zip/node_modules/@docusaurus/core/lib/server/plugins/init.js:27:10)
    at Object.loadPlugins (/.../my-framework/.yarn/$$virtual/@docusaurus-core-virtual-823a146269/0/cache/@docusaurus-core-npm-2.0.0-alpha.f37987f32-0083f3f5a5-294a73ee2e.zip/node_modules/@docusaurus/core/lib/server/plugins/index.js:50:35)
    at Object.load (/.../my-framework/.yarn/$$virtual/@docusaurus-core-virtual-823a146269/0/cache/@docusaurus-core-npm-2.0.0-alpha.f37987f32-0083f3f5a5-294a73ee2e.zip/node_modules/@docusaurus/core/lib/server/index.js:108:98)
```

So it's looking for those dependency packages in the root directory.

**Comment by Redeltaz** [comment]
In my project I had to use the typedoc command inside the lib, and put the output path into the docusaurus project like that:
`npx typedoc --out "../../docs/docs/${folderName}" "./src/index.ts"`

**Comment by tgreyuk** [comment]
This specific error should no longer happen with latest version.  Also as a general point TypeDoc 0.21 has introduced better monorepo support https://github.com/TypeStrong/typedoc#monorepos--workspaces
