### ISSUE TITLE
Sidebar not found

### ISSUE THREAD

**Issue by B4nan** [tgreyuk/typedoc-plugin-markdown#224]
I remember I had the very same issue some time ago, but can't find it. The sidebar is not generated soon enough with recent update (its the very latest version that broke it).

Failed CI build:

https://github.com/mikro-orm/mikro-orm/runs/2515932376#step:8:38

**Comment by tgreyuk** [comment]
Must be because of https://github.com/tgreyuk/typedoc-plugin-markdown/pull/217

Basically this means that manual sidebars no longer be maintained. However it should have been backward compatible so will see why this failed and patch it.

New implementation is to replace:

```
API: require('./typedoc-sidebar.js')
```

With:

```
'API': [
      {
        type: 'autogenerated',
        dirName: 'api', // 'api' is the 'out' directory
      },
    ],
```

**Comment by tgreyuk** [comment]
@B4nan  Fix in @docusaurus-plugin-markdown@0.14.1

**Comment by B4nan** [comment]
Perfect, thanks for the prompt response & fix, I can confirm it helped.

**Comment by B4nan** [comment]
FYI this is broken again, but the new way via `type: 'autogenerated'` works fine.

```ts
Info: Documentation generated at /Users/adamek/htdocs/mikro-orm/mikro-orm/docs/docs/api
Loading of version failed for version "current"
Error: Error loading {"type":"autogenerated","dirName":"/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/api"}: "dirName" must be a dir path relative to the docs folder root, and should not start or end with slash
    at assertIsAutogenerated (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars.js:65:15)
    at normalizeItem (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars.js:113:13)
    at arrayMap (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/lodash/lodash.js:653:23)
    at map (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/lodash/lodash.js:9622:14)
    at Function.flatMap (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/lodash/lodash.js:9325:26)
    at normalizeSidebar (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars.js:134:21)
    at /Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/lodash/lodash.js:13469:38
    at /Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/lodash/lodash.js:13468:7)
    at normalizeSidebars (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars.js:137:21)
    at Object.loadSidebars (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars.js:175:12)
    at doLoadVersion (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:102:56)
    at loadVersion (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:171:34)
    at Array.map (<anonymous>)
    at Object.loadContent (/Users/adamek/htdocs/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:179:68)
```
