### ISSUE TITLE
typedoc v0.22 breaks with "Package subpath './dist/lib/converter/plugins' is not defined by exports"

### ISSUE THREAD

**Issue by B4nan** [tgreyuk/typedoc-plugin-markdown#249]
There are some breaking changes in that version, so probably caused by that.

https://github.com/TypeStrong/typedoc/releases/tag/v0.22.0
https://github.com/mikro-orm/mikro-orm/runs/3572094787

```
[en] Creating an optimized production build...
Unable to build website for locale "en".
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/converter/plugins' is not defined by "exports" in /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/package.json
    at new NodeError (node:internal/errors:329:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:337:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:562:3)
    at resolveExports (node:internal/modules/cjs/loader:473:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:513:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:910:27)
    at Function.Module._resolveFilename (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc-plugin-markdown/dist/theme.js:13:19)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
```

**Comment by sambacha** [comment]
thanks @tgreyuk can confirm as well

**Comment by bennycode** [comment]
I also have this issue:

```
typedoc src/index.ts
Error: The plugin typedoc-plugin-markdown could not be loaded.
Error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/converter/plugins' is not defined by "exports" in /Users/bennycode/coinbase-pro-node/node_modules/typedoc/package.json
    at new NodeError (node:internal/errors:371:5)
```

I am using an Apple M1 MacBook with Node.js v16.8.0. Problem showed up when upgrading typedoc from 0.21.9 to 0.22.0.

**Comment by tgreyuk** [comment]
typedoc-plugin-markdown@3.11.0 should hopefully be compatible

**Comment by B4nan** [comment]
Yop, works fine, thanks!

**Comment by bennycode** [comment]
With v3.11.0 I am getting this error now:

> Info: Loaded plugin typedoc-plugin-markdown
> Error: Tried to set an option (disableOutputCheck) that was not declared.

**Comment by sstone1** [comment]
@tgreyuk @bennycode similar issue here, I now get: `Error: Tried to set an option (packages) that was not declared.`

**Comment by tgreyuk** [comment]
@bennycode @sstone1 this is due to breaking changes in typedoc 0.22. please see https://github.com/TypeStrong/typedoc/releases/tag/v0.22.0
