### ISSUE TITLE
Error using docusaurus: Class extends value undefined

### ISSUE THREAD

**Issue by sedghi** [tgreyuk/typedoc-plugin-markdown#255]
I'm getting the following error 

```js
2:22:51 PM: [en] Creating an optimized production build...
2:22:52 PM: Unable to build website for locale "en".
2:22:52 PM: TypeError: Class extends value undefined is not a constructor or null
2:22:52 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/typedoc-plugin-markdown/dist/theme.js:16:39)
2:22:52 PM:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
2:22:52 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2:22:52 PM:     at Module.load (internal/modules/cjs/loader.js:928:32)
2:22:52 PM:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2:22:52 PM:     at Module.require (internal/modules/cjs/loader.js:952:19)
2:22:52 PM:     at require (internal/modules/cjs/helpers.js:88:18)
2:22:52 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/typedoc-plugin-markdown/dist/index.js:7:17)
2:22:52 PM:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
2:22:52 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2:22:52 PM:     at Module.load (internal/modules/cjs/loader.js:928:32)
2:22:52 PM:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2:22:52 PM:     at Module.require (internal/modules/cjs/loader.js:952:19)
2:22:52 PM:     at require (internal/modules/cjs/helpers.js:88:18)
2:22:52 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/docusaurus-plugin-typedoc/dist/plugin.js:24:35)
2:22:52 PM:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

**Comment by tgreyuk** [comment]
hi. can you please confirm versions being used of the following?
- typedoc
- typedoc-plugin-markdown
- docusaurus-plugin-typedoc
- docusuaurus

thanks

**Comment by raimonkh** [comment]
Sorted by downgrading typedoc from 21.9 to 21.0
Docusaurus plugin to 0.15.0
typedoc plugin markdown to 3.10.0
also I had typescript updated to 4.4 so downgraded to 4.2

**Comment by mayur-bhandari** [comment]
I am facing a similar issue when running the typedoc command.

Command: `npx typedoc --options typedoc.json`

My typedoc.json file:

```
{
    "entryPoints": [
        ...
    ],
    "out": "doc",
    "excludePrivate": true,
    "excludeProtected": true,
    "excludeInternal": true,
    "disableSources": true,
    "readme": "none",
    "hideGenerator": true,
    "hideBreadcrumbs": true // getting issue with this property
}
```

I am using the below mentioned versions,

```
"typedoc": "^0.20.37",
"typedoc-plugin-markdown": "^3.11.3",
"typescript": "^3.9.10"
```

The error I am getting is as follows,

```
Error: The plugin /Users/mac-18/project/node_modules/typedoc-plugin-markdown could not be loaded.
Info: TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/mac-18/project/node_modules/typedoc-plugin-markdown/dist/theme.js:16:39)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/mac-18/project/node_modules/typedoc-plugin-markdown/dist/index.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: Tried to set an option (hideBreadcrumbs) that was not declared.
```

**Comment by wxsms** [comment]
same issue.

```
    "typedoc": "^0.21.4",
    "typedoc-plugin-markdown": "^3.11.7",
    "typescript": "^4.1.5",
```

**Comment by chbro** [comment]
same here
