### ISSUE TITLE
[typedoc-plugin-markdown] 3.11.9 The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by wxsms** [tgreyuk/typedoc-plugin-markdown#280]
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.dirname (node:path:654:5)
    at MarkdownTheme.getRelativeUrl (project\node_modules\typedoc-plugin-markdown\dist\theme.js:107:49)
    at Object.relativeURL (project\node_modules\typedoc-plugin-markdown\dist\resources\helpers\relative-url.js:9:25)
    at project\node_modules\typedoc-plugin-markdown\dist\resources\helpers\toc.js:12:126
    at Array.map (<anonymous>)
    at pushGroup (project\node_modules\typedoc-plugin-markdown\dist\resources\helpers\toc.js:12:45)
    at project\node_modules\typedoc-plugin-markdown\dist\resources\helpers\toc.js:32:25
    at Array.forEach (<anonymous>) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
```

I'm using with Vuepress v2. The 3.11.8 works fine. but error on 3.11.9. node.js v16.11.0.

**Comment by tgreyuk** [comment]
can you please try with vuepress-plugin-typedoc@0.10.1 - i couldn't actually replicate the issue but I think it should fix it. If not will investigate further. thanks.

**Comment by wxsms** [comment]
it works after upgrade vuepress-plugin-typedoc@0.10.1, thanks. closing due to problem solved.
