### ISSUE TITLE
Cannot read properties of undefined (reading 'qualifiedName')

### ISSUE THREAD

**Issue by jsbrain** [tgreyuk/typedoc-plugin-markdown#283]
```
TypeDoc exiting with unexpected error:
TypeError: Cannot read properties of undefined (reading 'qualifiedName')
    at Renderer.attemptExternalResolution (/repo/node_modules/typedoc/dist/lib/output/renderer.js:114:19)
    at Object.attemptExternalResolution (/repo/node_modules/typedoc-plugin-markdown/dist/resources/helpers/attemptExternalResolution.js:6:28)
    at getReferenceType (/repo/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:119:44)
    at ReferenceType.<anonymous> (/repo/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:10:20)
    at /repo/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:108:140
    at Array.map (<anonymous>)
    at /repo/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:107:29
    at Array.map (<anonymous>)
    at getFunctionType (/repo/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:100:39)
    at getReflectionType (/repo/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:69:15)
```

caused by

```js
    /**
     * Marked as internal for now. Using this requires the internal `getSymbol()` method on ReferenceType.
     * Someday that needs to be fixed so that this can be made public. ReferenceTypes really shouldn't store
     * symbols so that we don't need to keep the program around forever.
     * @internal
     */
    attemptExternalResolution(type) {
        if (!type.qualifiedName || !type.package) { // <- this
            return;
        }
        const resolvers = this.unknownSymbolResolvers.get(type.package);
        for (const resolver of resolvers || []) {
            const resolved = resolver(type.qualifiedName);
            if (resolved)
                return resolved;
        }
    }
```

in `node_modules/typedoc/dist/lib/output/renderer.js`.

This fixed it for me: `if (!type || !type.qualifiedName || !type.package) {` but not sure if it won't cause other problems.

```json
{
    ...,
    "typedoc": "^0.22.8",
    "typedoc-plugin-markdown": "^3.11.11",
    "typescript": "^4.4.4"
}
```

**Comment by chen86860** [comment]
Downgrade the version of `typedoc` to `0.22.10` is okay for me.

**Comment by tgreyuk** [comment]
Please try typedoc-plugin-markdown@3.11.12
