### ISSUE TITLE
Error while using with typedoc@0.23.1

### ISSUE THREAD

**Issue by Nokel81** [tgreyuk/typedoc-plugin-markdown#322]
I get the following error while trying to upgrade to the latest version of `typedoc`:

```
TypeError: text.replace is not a function
    at Array.<anonymous> (/repo/node_modules/typedoc-plugin-markdown/dist/resources/helpers/comment.js:74:25)
    at Array.wrapper (/repo/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (/repo/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:11:227)
    at prog (/repo/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
    at PageEvent.<anonymous> (/repo/node_modules/handlebars/dist/cjs/handlebars/helpers/with.js:32:14)
    at PageEvent.wrapper (/repo/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at Object.eval [as main] (eval at createFunctionContext (/repo/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:12:49)
    at main (/repo/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at ret (/repo/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at ret (/repo/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
```

Adding a `console.log` of that line (which is `text = text.replace(INCLUDE_PATTERN, (match, includesPath) => {`), I get something of the shape:

```js
[
  {
    kind: 'text',
    text: '# Extension API Reference\n' +
      '\n' +
      '## APIs\n' +
      '\n' +
      '- [Common](modules/Common.md)\n'
  }
]
```

**Comment by tgreyuk** [comment]
fix in typedoc-plugin-markdown@3.13.0
