### ISSUE TITLE
Plugin is broken with latest release [0.23.14] of typedoc

### ISSUE THREAD

**Issue by ShivamJoker** [tgreyuk/typedoc-plugin-markdown#344]
I am not sure why but from [0.23.14](https://github.com/TypeStrong/typedoc/releases/tag/v0.23.14) release the package is giving me this big error 

```sh
 npx typedoc --plugin typedoc-plugin-markdown --out docs src/index.ts --hideInPageTOC true --hideBreadcrumbs true --name "How to use?"
Loaded plugin typedoc-plugin-markdown
TypeDoc exiting with unexpected error:
TypeError: theme.owner.attemptExternalResolution is not a function
    at Object.attemptExternalResolution (/home/shivam/web/wiki-img/node_modules/.pnpm/typedoc-plugin-markdown@3.13.5_typedoc@0.23.14/node_modules/typedoc-plugin-markdown/dist/resources/helpers/attemptExternalResolution.js:6:28)
    at getReferenceType (/home/shivam/web/wiki-img/node_modules/.pnpm/typedoc-plugin-markdown@3.13.5_typedoc@0.23.14/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:119:44)
    at ReferenceType.<anonymous> (/home/shivam/web/wiki-img/node_modules/.pnpm/typedoc-plugin-markdown@3.13.5_typedoc@0.23.14/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:10:20)
    at Object.<anonymous> (/home/shivam/web/wiki-img/node_modules/.pnpm/typedoc-plugin-markdown@3.13.5_typedoc@0.23.14/node_modules/typedoc-plugin-markdown/dist/resources/helpers/signature-title.js:29:50)
    at Object.wrapper (/home/shivam/web/wiki-img/node_modules/.pnpm/handlebars@4.7.7/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at Object.eval [as main] (eval at createFunctionContext (/home/shivam/web/wiki-img/node_modules/.pnpm/handlebars@4.7.7/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:9:118)
    at main (/home/shivam/web/wiki-img/node_modules/.pnpm/handlebars@4.7.7/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at Object.ret (/home/shivam/web/wiki-img/node_modules/.pnpm/handlebars@4.7.7/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at Object.ret [as member.signature] (/home/shivam/web/wiki-img/node_modules/.pnpm/handlebars@4.7.7/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
    at Object.invokePartialWrapper [as invokePartial] (/home/shivam/web/wiki-img/node_modules/.pnpm/handlebars@4.7.7/node_modules/handlebars/dist/cjs/handlebars/runtime.js:88:46)
```

**Comment by tgreyuk** [comment]
fix in typedoc-plugin-markdown@3.13.6
