### ISSUE TITLE
TypeError when using 3.15 with TypeDoc 0.23.28

### ISSUE THREAD

**Issue by Jason3S** [tgreyuk/typedoc-plugin-markdown#407]
Maybe 3.15 should have been marked as a breaking change?

```
TypeDoc exiting with unexpected error:
TypeError: template is not a function
    at MarkdownTheme.render (/home/runner/work/cspell/cspell/node_modules/.pnpm/typedoc-plugin-markdown@3.15.1_typedoc@0.23.28/node_modules/typedoc-plugin-markdown/dist/theme.js:62:44)
    at Renderer.renderDocument (/home/runner/work/cspell/cspell/node_modules/.pnpm/typedoc@0.23.28_typescript@5.0.4/node_modules/typedoc/dist/lib/output/renderer.js:180:40)
    at /home/runner/work/cspell/cspell/node_modules/.pnpm/typedoc@0.23.28_typescript@5.0.4/node_modules/typedoc/dist/lib/output/renderer.js:158:22
    at Array.forEach (<anonymous>)
    at Renderer.render (/home/runner/work/cspell/cspell/node_modules/.pnpm/typedoc@0.23.28_typescript@5.0.4/node_modules/typedoc/dist/lib/output/renderer.js:156:25)
    at async Application.generateDocs (/home/runner/work/cspell/cspell/node_modules/.pnpm/typedoc@0.23.28_typescript@5.0.4/node_modules/typedoc/dist/lib/application.js:287:9)
    at async run (/home/runner/work/cspell/cspell/node_modules/.pnpm/typedoc@0.23.28_typescript@5.0.4/node_modules/typedoc/bin/typedoc:115:13)
```

**Comment by fabrizio-vitale-deltatre** [comment]
Downgrading to `3.14.0` fixes this issue:

```diff
-    "typedoc-plugin-markdown": "^3.14.0",
+    "typedoc-plugin-markdown": "3.14.0",
```

**Comment by tgreyuk** [comment]
> Maybe 3.15 should have been marked as a breaking change?

Maybe - although it is marked with a peer dependency of `"typedoc": ">=0.24.0"`
