### ISSUE TITLE
Error: Missing helper: "relativeURL"

### ISSUE THREAD

**Issue by joelday** [tgreyuk/typedoc-plugin-markdown#41]
I'm getting this exception when generating documentation with `--theme markdown`.

```
/Users/.../node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19
      throw new _exception2['default']('Missing helper: "' + arguments[arguments.length - 1].name + '"');
      ^
Error: Missing helper: "relativeURL"
    at DeclarationReflection.<anonymous> (/Users/.../node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
    at eval (eval at createFunctionContext (/Users/.../node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:8:100)
    at Object.prog [as fn] (/Users/.../node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at DeclarationReflection.ifDisplayIndexItem (/Users/.../node_modules/typedoc-plugin-markdown/dist/theme/helpers/ifDisplayIndexItem.js:10:21)
    at eval (eval at createFunctionContext (/Users/.../node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:116)
    at prog (/Users/.../node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/Users/.../node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at ReflectionGroup.<anonymous> (/Users/.../node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at eval (eval at createFunctionContext (/Users/.../node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:8:31)
    at Object.prog [as fn] (/Users/.../node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
```

I'm currently using:
```
"typescript": "^3.1.3",    
"typedoc": "0.13.0",
"typedoc-plugin-markdown": "1.1.17"
```

Thanks!

**Comment by tgreyuk** [comment]
Hi @joelday ...

If you are running from the shell then you will need to point to locally installed typedoc ie:

```
$ node_modules/.bin/typedoc --theme markdown
```

or just define an npm script

```
"scripts": {
 "docs": "typedoc --theme markdown"
}
```

Let me know if this fixes and will close...

thanks.

**Comment by joelday** [comment]
Thanks @tgreyuk!
