### ISSUE TITLE
[bug] 4.0.0-next.6 ReflectionKind.singularString is not a function

### ISSUE THREAD

**Issue by paularmstrong** [tgreyuk/typedoc-plugin-markdown#411]
Suddenly getting this error upgrading from 4.0.0-next.3 to 4.0.0-next.6. I'm not sure how to trace this to determine if there's an issue on my side or in this package, but I'm leaning toward the latter.

```
TypeDoc exiting with unexpected error:
TypeError: typedoc_1.ReflectionKind.singularString is not a function
    at MarkdownTheme.getUrl (./node_modules/typedoc-plugin-markdown/dist/theme.:71)
    at MarkdownTheme.buildUrls (./node_modules/typedoc-plugin-markdown/dist/js:89:30)
    at ./node_modules/typedoc-plugin-markdown/dist/theme.js:82:18
    at Array.forEach (<anonymous>)
    at MarkdownTheme.getUrls (./node_modules/typedoc-plugin-markdown/dist/js:81:73)
    at Renderer.render (./node_modules/typedoc/dist/lib/output/renderer.:34)
    at async Application.generateDocs (./node_modules/typedoc/dist/lib/ation.js:287:9)
    at async run (./node_modules/typedoc/bin/typedoc:115:13)
```

**Comment by tgreyuk** [comment]
Latest version requires Typedoc 0.24 as peer dependency?
