### ISSUE TITLE
Doesn't work with typedoc 0.14.0

### ISSUE THREAD

**Issue by SkeLLLa** [tgreyuk/typedoc-plugin-markdown#44]
Updating typedoc to 0.14.0 cause following error with this plugin. That's probably connected to typescript upgrade.

```
TypeError: Class constructor ConverterComponent cannot be invoked without 'new'
    at new MarkdownPlugin (/home/user/something/node_modules/typedoc-plugin-markdown/dist/plugin.js:31:42)
    at Converter.addComponent (/home/user/something/node_modules/typedoc/dist/lib/utils/component.js:123:19)
    at Converter.addComponent (/home/user/something/node_modules/typedoc/dist/lib/converter/converter.js:28:33)
    at module.exports (/home/user/something/node_modules/typedoc-plugin-markdown/dist/index.js:36:19)
```

**Comment by tgreyuk** [comment]
Thanks. The main issue was that 0.14.0 is compiled to es2015 (from es5). Fixed in 1.1.21.
