### ISSUE TITLE
Bug: When `entryPointStrategy` is set to `expand`, docusaurus complains about broken links

### ISSUE THREAD

**Issue by lengors** [tgreyuk/typedoc-plugin-markdown#486]
I assume this is a bug, but when I set `entryPointStrategy` to ` expand`, I get the following error when building docusaurus:
```
[ERROR] Unable to build website for locale en.
[ERROR] Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /docs/api/core/shutdown/:
   -> linking to null (resolved as: /docs/api/core/shutdown/null)

- On source page path = /docs/api/test/:
   -> linking to null (resolved as: /docs/api/test/null)

    at throwError (C:\Users\pedro\Projects\engine-test-gh-pages\node_modules\@docusaurus\logger\lib\index.js:76:11)
    at handleBrokenLinks (C:\Users\pedro\Projects\engine-test-gh-pages\node_modules\@docusaurus\core\lib\server\brokenLinks.js:153:47)
    at async buildLocale (C:\Users\pedro\Projects\engine-test-gh-pages\node_modules\@docusaurus\core\lib\commands\build.js:186:5)
    at async tryToBuildLocale (C:\Users\pedro\Projects\engine-test-gh-pages\node_modules\@docusaurus\core\lib\commands\build.js:41:20)
    at async mapAsyncSequential (C:\Users\pedro\Projects\engine-test-gh-pages\node_modules\@docusaurus\utils\lib\jsUtils.js:34:24)
    at async Command.build (C:\Users\pedro\Projects\engine-test-gh-pages\node_modules\@docusaurus\core\lib\commands\build.js:76:21)
```

I've tried both with `latest` channel:
- `typedoc`: `0.25.2`
- `typedoc-plugin-markdown`: `3.16.0`
- `docusaurus-plugin-typedoc`: `0.20.2`
And `next` channel:
- `typedoc`: `0.25.2`
- `typedoc-plugin-markdown`: `4.0.0-next.24`
- `docusaurus-plugin-typedoc`: `1.0.0-next.18`

I like that `next` channel separates functions and what not, even when not using the `expand` strategy, but would still prefer `expand`, but I don't know if it's possible to fix this issue.

**Comment by tgreyuk** [comment]
Thanks @lengors - would you be able to share your config on a public repo?

**Comment by lengors** [comment]
@tgreyuk Yes, I can. Here is the repository: https://github.com/lengors/issue-demo

One thing to note is that when setting `readme` to `"none"`, the issue doesn't occur. My guess is that because without it, the markdown plugin doesn't generate a `module.md` which I believe is what's causing the conflict with `modules/index.md`.

**Comment by tgreyuk** [comment]
This will no longer throw an error in lastest `next` version.

**Comment by lengors** [comment]
> This will no longer throw an error in lastest `next` version.

Awesome. Thank you. By the way, v3 of Docusaurus was released yesterday, I haven't tested to see if the plugin is compatible atm or not, but do you have any plans to officially support it?

**Comment by tgreyuk** [comment]
Yes - if you use the latest version Docusaurus v3 should be supported (obviouslly let me know if any issues though).
