### ISSUE TITLE
Adding support for typedoc-plugin-coverage 

### ISSUE THREAD

**Issue by SalahAdDin** [tgreyuk/typedoc-plugin-markdown#573]
Hello again,

Right now we are testing the [coverage plugin](https://github.com/Gerrit0/typedoc-plugin-coverage) for creating a badge showing the documentation coverage on the API documentation; unfortunately, it does not work:
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/5034215/8df71835-b852-4644-b690-d576beb3ce4a)

However, the badge is created as an _svg_ file:
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/5034215/21ac7f19-5fcf-49b1-9899-b655ede61ac1)

It should be enough to automatically add it to the `intro.md` file to show it.

What do you think?

**Comment by tgreyuk** [comment]
I think that plugin simply creates the SVG. Where exactly would you want it placed? Underneath the API heading on index page only?

**Comment by SalahAdDin** [comment]
> I think that plugin simply creates the SVG. Where exactly would you want it placed? Underneath the API heading on index page only?

Place in the index would be enough, but if it is added to the API heading, I would be amazing!

**Comment by tgreyuk** [comment]
Can you make sure you are using the latest version of all plugins please?

**Comment by SalahAdDin** [comment]
> Can you make sure you are using the latest version of all plugins, please?

Yeah, they are in the latest version:
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/5034215/1c633ad1-18fb-4124-9674-1d03cc52222e)

**Comment by tgreyuk** [comment]
> Yeah, they are in the latest version:

please update to 4.0.0-next.53

**Comment by SalahAdDin** [comment]
I did it, and It still does not work:
![image](https://github.com/tgreyuk/typedoc-plugin-markdown/assets/5034215/320da082-b117-4cb2-a6ec-b23363c834ab)
```bash
ownHooks' not found. The requested module 'typedoc-plugin-markdown' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'typedoc-plugin-markdown';
const { MarkdownHooks } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
    at async loadPlugins (/home/luisalaguna/Projects/TRT/twe_fe_next/docs/node_modules/.pnpm/typedoc@0.25.7_typescript@5.3.3/node_modules/typedoc/dist/lib/utils/plugins.js:23:32)
    at async Application.bootstrapWithPlugins (/home/luisalaguna/Projects/TRT/twe_fe_next/docs/node_modules/.pnpm/typedoc@0.25.7_typescript@5.3.3/node_modules/typedoc/dist/lib/application.js:194:13)
    at async generateTypedoc (/home/luisalaguna/Projects/TRT/twe_fe_next/docs/node_modules/.pnpm/docusaurus-plugin-typedoc@1.0.0-next.27_typedoc-plugin-markdown@4.0.0-next.50/node_modules/docusaurus-plugin-typedoc/dist/plugin.js:65:17)
    at async Object.pluginDocusaurus [as plugin] (/home/luisalaguna/Projects/TRT/twe_fe_next/docs/node_modules/.pnpm/docusaurus-plugin-typedoc@1.0.0-next.27_typedoc-plugin-markdown@4.0.0-next.50/node_modules/docusaurus-plugin-typedoc/dist/plugin.js:38:9)
    at async initializePlugin (/home/luisalaguna/Projects/TRT/twe_fe_next/docs/node_modules/.pnpm/@docusaurus+core@3.1.1_@docusaurus+types@3.1.1_eslint@8.56.0_react-dom@18.2.0_react@18.2.0_typescript@5.3.3/node_modules/@docusaurus/core/lib/server/plugins/init.js:83:32)
    at async Promise.all (index 5)
[warning] TypeDoc has been loaded multiple times. This is commonly caused by plugins which have their own installation of TypeDoc. The loaded paths are:
        /home/luisalaguna/Projects/TRT/twe_fe_next/docs/node_modules/.pnpm/typedoc@0.25.7_typescript@5.3.3/node_modules/typedoc
        /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/typedoc@0.25.8_typescript@5.3.3/node_modules/typedoc
typedoc-copy-coverage.mjs:2:10 - error TS2305: Module '"typedoc-plugin-markdown"' has no exported member 'MarkdownHooks'.

2 import { MarkdownHooks } from "typedoc-plugin-markdown";
```

**Comment by SalahAdDin** [comment]
Done, it works cool!

Thanks !

**Comment by SalahAdDin** [comment]
> > Yeah, they are in the latest version:
> 
> please update to 4.0.0-next.53

Done, it works!

**Comment by SalahAdDin** [comment]
> > Yeah, they are in the latest version:
> 
> please update to 4.0.0-next.53

Done, it works!
