### ISSUE TITLE
typedoc-plugin-markdown@4.0.0-next.57: TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by ocavue** [tgreyuk/typedoc-plugin-markdown#595]
After updating typedoc-plugin-markdown from 4.0.0-next.55 to 4.0.0-next.57, I get the following error:

```
> typedoc

[info] Loaded plugin typedoc-plugin-markdown
[info] Converting project at ./packages/prosekit
[info] Merging converted projects
TypeDoc exiting with unexpected error:
TypeError: Cannot read properties of undefined (reading 'push')
    at processChildren (file:///home/projects/mklivgwqq.github/node_modules/.pnpm/typedoc-plugin-markdown@4.0.0-next.57_typedoc@0.25.13/node_modules/typedoc-plugin-markdown/dist/theme/core/navigation-builder.js:222:30)
    at eval (file:///home/projects/mklivgwqq.github/node_modules/.pnpm/typedoc-plugin-markdown@4.0.0-next.57_typedoc@0.25.13/node_modules/typedoc-plugin-markdown/dist/theme/core/navigation-builder.js:170:24)
    at Array.reduce (<anonymous>)
    at getGroupChildren (file:///home/projects/mklivgwqq.github/node_modules/.pnpm/typedoc-plugin-markdown@4.0.0-next.57_typedoc@0.25.13/node_modules/typedoc-plugin-markdown/dist/theme/core/navigation-builder.js:154:14)
    at buildNavigationFromProject (file:///home/projects/mklivgwqq.github/node_modules/.pnpm/typedoc-plugin-markdown@4.0.0-next.57_typedoc@0.25.13/node_modules/typedoc-plugin-markdown/dist/theme/core/navigation-builder.js:104:38)
    at buildNavigation (file:///home/projects/mklivgwqq.github/node_modules/.pnpm/typedoc-plugin-markdown@4.0.0-next.57_typedoc@0.25.13/node_modules/typedoc-plugin-markdown/dist/theme/core/navigation-builder.js:39:13)
    at MarkdownTheme.getNavigation (file:///home/projects/mklivgwqq.github/node_modules/.pnpm/typedoc-plugin-markdown@4.0.0-next.57_typedoc@0.25.13/node_modules/typedoc-plugin-markdown/dist/theme/markdown-theme.js:99:57)
    at _classThis.render (file:///home/projects/mklivgwqq.github/node_modules/.pnpm/typedoc-plugin-markdown@4.0.0-next.57_typedoc@0.25.13/node_modules/typedoc-plugin-markdown/dist/app/renderer/overrides.js:85:36)
    at _classThis.generateDocs (file:///home/projects/mklivgwqq.github/node_modules/.pnpm/typedoc-plugin-markdown@4.0.0-next.57_typedoc@0.25.13/node_modules/typedoc-plugin-markdown/dist/app/renderer/overrides.js:45:25)
    at run (file:///home/projects/mklivgwqq.github/node_modules/.pnpm/typedoc@0.25.13_typescript@5.4.5/node_modules/typedoc/dist/lib/cli.js:118:23)
```

I set up a mini repo to reproduce this issue.

1. Open https://stackblitz.com/github/issueset/typedoc-markdown-4-0-0-next-57
2. Run `pnpm install && pnpm run build` and you will see the error
3. Downgrade the verison number of typedoc-plugin-markdown in package.json to `4.0.0-next.55`
4. Run `pnpm install && pnpm run build` again and no error this time

**Comment by tgreyuk** [comment]
@ocavue thanks for the detailed description. I can confirm fixed in `4.0.0-next.58`
