### ISSUE TITLE
4.0.0-next.58: These sidebar document ids do not exist

### ISSUE THREAD

**Issue by axel7083** [tgreyuk/typedoc-plugin-markdown#597]
Something went wrong with the `/` used for the sidebar.

```logs
Error: Unable to build website for locale en.
    at tryToBuildLocale (C:\Users\axels\Documents\github\redhat\podman-desktop\node_modules\@docusaurus\core\lib\commands\build.js:55:19)
    at async mapAsyncSequential (C:\Users\axels\Documents\github\redhat\podman-desktop\node_modules\@docusaurus\utils\lib\jsUtils.js:44:24)
    at async Command.build (C:\Users\axels\Documents\github\redhat\podman-desktop\node_modules\@docusaurus\core\lib\commands\build.js:82:21) {
  [cause]: Error: Invalid sidebar file at "sidebars-api.js".
  These sidebar document ids do not exist:
  - classes\CancellationTokenSource
  - classes\Disposable
  - classes\EventEmitter
  - classes\TelemetryTrustedValue
  - classes\Uri

....

  Available document ids are:
  - classes/CancellationTokenSource
  - classes/Disposable
  - classes/EventEmitter
  - classes/TelemetryTrustedValue
  - classes/Uri
```

**Comment by tgreyuk** [comment]
Thanks - issue handling windows path separators properly!

Fix versions:
typedoc-plugin-markdown@4.0.0-next.58
docusaurus-plugin-typedoc@1.0.0-next.30
