### ISSUE TITLE
Upgrading from 2.1.1 to 2.1.3 leads to TypeError

### ISSUE THREAD

**Issue by kaiyoma** [tgreyuk/typedoc-plugin-markdown#85]
After upgrading this plugin, if I run typedoc, I get a crash:

```
.../node_modules/typedoc-plugin-markdown/dist/theme/helpers/parameter-table.js:25
            typeOut.toString().replace(/\|/g, plugin_1.MarkdownPlugin.theme instanceof theme_docusaurus_1.DocusaurusTheme ? '&#124;' : '\\|'),
                    ^

TypeError: Cannot read property 'toString' of undefined
    at rows.map.parameter (.../node_modules/typedoc-plugin-markdown/dist/theme/helpers/parameter-table.js:25:21)
    at Array.map (<anonymous>)
    at Array.parameterTable (.../node_modules/typedoc-plugin-markdown/dist/theme/helpers/parameter-table.js:20:23)
    at eval (eval at createFunctionContext (.../node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:6:197)
    at prog (.../node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at ParameterReflection.<anonymous> (.../node_modules/handlebars/dist/cjs/handlebars/helpers/with.js:22:14)
    at eval (eval at createFunctionContext (.../node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:6:34)
    at Object.prog [as fn] (.../node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at ParameterReflection.<anonymous> (.../node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:19:22)
    at eval (eval at createFunctionContext (.../node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:6:32)
```

This is happening with version 0.15.0 of typedoc.

**Comment by tgreyuk** [comment]
thanks @kaiyoma ... the latest version (2.1.4) should not throw this error, but let me know if anything looks wrong in any of the parameter definitions as I am not 100% sure of what the cause was. thanks.
